#![allow(dead_code, unused_imports)]

//! Admin management handlers (staff lifecycle, content, career management,
//! media uploads, and presigned document URL generation).
//! Protected by Role::Admin — see middleware::auth.

use worker::*;

use crate::email::send_onboarding_email;
use crate::middleware::auth::SessionContext;
use crate::models::career::{Application, ApplicationDocument, ApplicationStatus, Career, CareerUpdate, DocumentMeta};
use crate::router::{DbError, ValidationError, WorkerError, error_to_response};
use crate::storage::r2::{extension_from_mime, generate_presigned_url, r2_put_public};
use crate::storage::validator::{
    detect_mime_from_magic_bytes, sanitise_filename, ALLOWED_IMAGE_MIMES, MAX_IMAGE_SIZE,
};

// ---------------------------------------------------------------------------
// Allowed employment types
// ---------------------------------------------------------------------------

const ALLOWED_CAREER_TYPES: &[&str] = &["Full-Time", "Part-Time", "Contract", "Internship"];

// ---------------------------------------------------------------------------
// GET /api/admin/careers
// ---------------------------------------------------------------------------

/// Return all career listings regardless of active status.
///
/// Requires Admin role (enforced by router).
///
/// Requirements: 5.7
pub async fn list_admin_careers(
    _req: &Request,
    env: &Env,
    _ctx: SessionContext,
) -> Result<Response> {
    let db = env
        .d1("DB")
        .map_err(|e| WorkerError::Internal(e.to_string()))?;

    let results = db
        .prepare(
            "SELECT id, slug, title, description_md, department, type, active, created_at \
             FROM career ORDER BY created_at DESC",
        )
        .all()
        .await
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?;

    let careers: Vec<Career> = results
        .results::<Career>()
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?;

    Response::from_json(&careers)
        .map(|r| r.with_status(200))
        .map_err(|e| WorkerError::Internal(e.to_string()).into())
}

// ---------------------------------------------------------------------------
// POST /api/admin/careers
// ---------------------------------------------------------------------------

/// Create a new career listing.
///
/// Expects JSON body `{ slug, title, description_md?, department?, type, active? }`.
/// Validates `type` ∈ `{Full-Time, Part-Time, Contract, Internship}`.
/// Returns HTTP 201 with the created resource.
///
/// Requires Admin role (enforced by router).
///
/// Requirements: 5.2, 5.5
pub async fn create_career(
    mut req: Request,
    env: &Env,
    _ctx: SessionContext,
) -> Result<Response> {
    // ── Parse body ───────────────────────────────────────────────────────────
    let body: serde_json::Value = req
        .json()
        .await
        .unwrap_or(serde_json::Value::Object(serde_json::Map::new()));

    let slug = body
        .get("slug")
        .and_then(|v| v.as_str())
        .unwrap_or("")
        .trim()
        .to_string();

    let title = body
        .get("title")
        .and_then(|v| v.as_str())
        .unwrap_or("")
        .trim()
        .to_string();

    let description_md = body
        .get("description_md")
        .and_then(|v| v.as_str())
        .unwrap_or("")
        .to_string();

    let department = body
        .get("department")
        .and_then(|v| v.as_str())
        .unwrap_or("")
        .to_string();

    let career_type = body
        .get("type")
        .and_then(|v| v.as_str())
        .unwrap_or("")
        .to_string();

    // active defaults to true when not supplied
    let active = body
        .get("active")
        .and_then(|v| v.as_bool())
        .unwrap_or(true);

    // ── Validate required fields ─────────────────────────────────────────────
    if slug.is_empty() || title.is_empty() {
        return error_to_response(WorkerError::Validation(
            ValidationError::InvalidInput("slug and title are required".into()),
        ));
    }

    // ── Validate type (Req 5.2) ──────────────────────────────────────────────
    if !ALLOWED_CAREER_TYPES.contains(&career_type.as_str()) {
        return error_to_response(WorkerError::Validation(
            ValidationError::InvalidInput(
                "type must be one of: Full-Time, Part-Time, Contract, Internship".into(),
            ),
        ));
    }

    let db = env
        .d1("DB")
        .map_err(|e| WorkerError::Internal(e.to_string()))?;

    // ── Insert the new career row ─────────────────────────────────────────────
    // id is auto-generated by DEFAULT (lower(hex(randomblob(16))))
    let active_int: i64 = if active { 1 } else { 0 };

    db.prepare(
        "INSERT INTO career (slug, title, description_md, department, type, active) \
         VALUES (?1, ?2, ?3, ?4, ?5, ?6)",
    )
    .bind(&[
        slug.clone().into(),
        title.into(),
        description_md.into(),
        department.into(),
        career_type.into(),
        active_int.into(),
    ])
    .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?
    .run()
    .await
    .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?;

    // ── Re-query the inserted row ────────────────────────────────────────────
    let career = db
        .prepare(
            "SELECT id, slug, title, description_md, department, type, active, created_at \
             FROM career WHERE slug = ?1",
        )
        .bind(&[slug.into()])
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?
        .first::<Career>(None)
        .await
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?
        .ok_or_else(|| WorkerError::Internal("Career row missing after insert".into()))?;

    Response::from_json(&career)
        .map(|r| r.with_status(201))
        .map_err(|e| WorkerError::Internal(e.to_string()).into())
}

// ---------------------------------------------------------------------------
// PATCH /api/admin/careers/:id
// ---------------------------------------------------------------------------

/// Update an existing career listing by id.
///
/// Accepts a partial JSON body. Only fields present in the body are updated.
/// Validates `type` if provided.
/// Returns HTTP 200 with the updated resource.
///
/// Requires Admin role (enforced by router).
///
/// Requirements: 5.2, 5.6
pub async fn patch_career(
    mut req: Request,
    env: &Env,
    _ctx: SessionContext,
    id: &str,
) -> Result<Response> {
    let body: serde_json::Value = req
        .json()
        .await
        .unwrap_or(serde_json::Value::Object(serde_json::Map::new()));

    let db = env
        .d1("DB")
        .map_err(|e| WorkerError::Internal(e.to_string()))?;

    // ── Validate career_type if provided ─────────────────────────────────────
    if let Some(t) = body.get("type").and_then(|v| v.as_str()) {
        if !ALLOWED_CAREER_TYPES.contains(&t) {
            return error_to_response(WorkerError::Validation(
                ValidationError::InvalidInput(
                    "type must be one of: Full-Time, Part-Time, Contract, Internship".into(),
                ),
            ));
        }
    }

    // Build SET clauses dynamically — only include fields present in the body
    let mut set_clauses: Vec<String> = Vec::new();
    let mut bindings: Vec<wasm_bindgen::JsValue> = Vec::new();
    let mut param_idx: u32 = 1;

    macro_rules! push_field {
        ($json_key:expr, $col:expr, $extractor:expr) => {
            if let Some(val) = body.get($json_key).and_then($extractor) {
                set_clauses.push(format!("{} = ?{}", $col, param_idx));
                bindings.push(val.into());
                param_idx += 1;
            }
        };
    }

    push_field!("title",          "title",          |v| v.as_str().map(|s| s.to_string()));
    push_field!("description_md", "description_md", |v| v.as_str().map(|s| s.to_string()));
    push_field!("department",     "department",      |v| v.as_str().map(|s| s.to_string()));
    push_field!("type",           "type",            |v| v.as_str().map(|s| s.to_string()));
    push_field!("slug",           "slug",            |v| v.as_str().map(|s| s.to_string()));

    // active is a bool → stored as integer
    if let Some(active_bool) = body.get("active").and_then(|v| v.as_bool()) {
        let active_int: i64 = if active_bool { 1 } else { 0 };
        set_clauses.push(format!("active = ?{}", param_idx));
        bindings.push(active_int.into());
        param_idx += 1;
    }

    if set_clauses.is_empty() {
        return error_to_response(WorkerError::Validation(
            ValidationError::InvalidInput("No updatable fields provided".into()),
        ));
    }

    // Always bump updated_at for careers — the schema stores created_at only,
    // but we add updated_at if it exists; if not, we skip it gracefully.
    // (Schema only has created_at for career table per DDL.)

    let sql = format!(
        "UPDATE career SET {} WHERE id = ?{}",
        set_clauses.join(", "),
        param_idx
    );
    bindings.push(id.to_string().into());

    db.prepare(&sql)
        .bind(&bindings)
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?
        .run()
        .await
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?;

    // ── Re-query updated row ─────────────────────────────────────────────────
    let career = db
        .prepare(
            "SELECT id, slug, title, description_md, department, type, active, created_at \
             FROM career WHERE id = ?1",
        )
        .bind(&[id.into()])
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?
        .first::<Career>(None)
        .await
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?
        .ok_or(WorkerError::NotFound)?;

    Response::from_json(&career)
        .map(|r| r.with_status(200))
        .map_err(|e| WorkerError::Internal(e.to_string()).into())
}

// ---------------------------------------------------------------------------
// GET /api/admin/applications
// ---------------------------------------------------------------------------

/// Return all applications ordered by `applied_at DESC`.
///
/// Requires Admin role (enforced by router).
///
/// Requirements: 3.6, 7.3
pub async fn list_applications(
    _req: &Request,
    env: &Env,
    _ctx: SessionContext,
) -> Result<Response> {
    let db = env
        .d1("DB")
        .map_err(|e| WorkerError::Internal(e.to_string()))?;

    let results = db
        .prepare(
            "SELECT id, career_id, applicant_name, applicant_email, cover_letter, \
             status, applied_at, updated_at \
             FROM application ORDER BY applied_at DESC",
        )
        .all()
        .await
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?;

    let applications: Vec<Application> = results
        .results::<Application>()
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?;

    Response::from_json(&applications)
        .map(|r| r.with_status(200))
        .map_err(|e| WorkerError::Internal(e.to_string()).into())
}

// ---------------------------------------------------------------------------
// Applicant lifecycle transition helpers (Req 7.1)
// ---------------------------------------------------------------------------

/// Allowed `(current, next)` status transitions as specified in design
/// section 9.1 and requirement 7.1.
///
/// ```text
/// Applied       → Interviewing
/// Interviewing  → Offered
/// Interviewing  → Rejected
/// Offered       → Hired
/// Offered       → Rejected
/// ```
pub fn is_allowed_transition(current: ApplicationStatus, next: ApplicationStatus) -> bool {
    matches!(
        (current, next),
        (ApplicationStatus::Applied, ApplicationStatus::Interviewing)
            | (ApplicationStatus::Interviewing, ApplicationStatus::Offered)
            | (ApplicationStatus::Interviewing, ApplicationStatus::Rejected)
            | (ApplicationStatus::Offered, ApplicationStatus::Hired)
            | (ApplicationStatus::Offered, ApplicationStatus::Rejected)
    )
}

/// Convert an `ApplicationStatus` to its canonical string value as stored
/// in D1 (matches the `CHECK` constraint in the schema).
fn status_to_str(s: ApplicationStatus) -> &'static str {
    match s {
        ApplicationStatus::Applied => "Applied",
        ApplicationStatus::Interviewing => "Interviewing",
        ApplicationStatus::Offered => "Offered",
        ApplicationStatus::Hired => "Hired",
        ApplicationStatus::Rejected => "Rejected",
    }
}

// ---------------------------------------------------------------------------
// PATCH /api/admin/applications/:id/status
// ---------------------------------------------------------------------------

/// Transition an application to a new status.
///
/// Request body: `{ "status": "<TargetStatus>" }`
///
/// Behaviour:
/// - Returns HTTP 404 if the application does not exist.
/// - Returns HTTP 400 if the requested transition is not in the allowed set.
/// - On success, updates `status` and `updated_at`, returns HTTP 200.
///
/// Requires Admin role (enforced by router).
///
/// Requirements: 7.1, 7.2, 7.3
pub async fn patch_application_status(
    mut req: Request,
    env: &Env,
    _ctx: SessionContext,
    id: &str,
) -> Result<Response> {
    // ── Parse body ───────────────────────────────────────────────────────────
    let body: serde_json::Value = req
        .json()
        .await
        .unwrap_or(serde_json::Value::Object(serde_json::Map::new()));

    let target_status_str = match body.get("status").and_then(|v| v.as_str()) {
        Some(s) => s.to_string(),
        None => {
            return error_to_response(WorkerError::Validation(ValidationError::InvalidInput(
                "status field is required".into(),
            )));
        }
    };

    // Deserialise the target status from the string value
    let target_status: ApplicationStatus =
        match serde_json::from_value(serde_json::Value::String(target_status_str.clone())) {
            Ok(s) => s,
            Err(_) => {
                return error_to_response(WorkerError::Validation(ValidationError::InvalidInput(
                    format!("Unknown status: {}", target_status_str),
                )));
            }
        };

    let db = env
        .d1("DB")
        .map_err(|e| WorkerError::Internal(e.to_string()))?;

    // ── Load current application status from D1 ───────────────────────────
    // We only need the `status` field here; query only what we need.
    let row = db
        .prepare("SELECT id, career_id, applicant_name, applicant_email, cover_letter, status, applied_at, updated_at FROM application WHERE id = ?1")
        .bind(&[id.into()])
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?
        .first::<Application>(None)
        .await
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?;

    let application = match row {
        Some(a) => a,
        None => return error_to_response(WorkerError::NotFound),
    };

    let current_status = application.status;

    // ── Validate the transition (Req 7.1, 7.2) ───────────────────────────────
    if !is_allowed_transition(current_status, target_status) {
        let msg = format!(
            "Invalid transition from {} to {}",
            status_to_str(current_status),
            status_to_str(target_status)
        );
        return Response::from_json(&serde_json::json!({ "error": msg }))
            .map(|r| r.with_status(400))
            .map_err(|e| e.into());
    }

    // ── Execute the status update (Req 7.3) ──────────────────────────────────
    db.prepare(
        "UPDATE application SET status = ?1, updated_at = unixepoch() WHERE id = ?2",
    )
    .bind(&[status_to_str(target_status).into(), id.into()])
    .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?
    .run()
    .await
    .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?;

    Response::from_json(&serde_json::json!({ "id": id, "status": status_to_str(target_status) }))
        .map(|r| r.with_status(200))
        .map_err(|e| WorkerError::Internal(e.to_string()).into())
}

// ---------------------------------------------------------------------------
// POST /api/admin/applications/:id/hire
// ---------------------------------------------------------------------------

/// Hire an applicant: atomically promote their application to `Hired`, create
/// a `staff` row, create a `staff_lifecycle` row with `Probation` status, and
/// dispatch an onboarding email.
///
/// Expects JSON body `{ probation_months: u8 }` where the value must be
/// in the range 3–6 inclusive.
///
/// Returns HTTP 201 `{ "staff_id": "..." }` on success.
/// Returns HTTP 400 if `probation_months` is out of range.
/// Returns HTTP 404 if the application does not exist.
/// Returns HTTP 400 if the application is not in `Offered` status.
/// Returns HTTP 500 (with best-effort compensating deletes) on any DB failure.
///
/// Requires Admin role (enforced by router).
///
/// Requirements: 7.4, 7.5, 7.6, 7.7, 7.8
pub async fn hire_applicant(
    mut req: Request,
    env: &Env,
    _ctx: SessionContext,
    application_id: &str,
) -> Result<Response> {
    // ── Parse and validate body ──────────────────────────────────────────────
    let body: serde_json::Value = req
        .json()
        .await
        .unwrap_or(serde_json::Value::Object(serde_json::Map::new()));

    let probation_months = match body.get("probation_months").and_then(|v| v.as_u64()) {
        Some(n) => n,
        None => {
            return error_to_response(WorkerError::Validation(ValidationError::InvalidInput(
                "probation_months is required and must be a positive integer".into(),
            )));
        }
    };

    // Req 7.4, 7.5 — valid range is [3, 6] inclusive
    if !(3..=6).contains(&probation_months) {
        return error_to_response(WorkerError::Validation(ValidationError::InvalidInput(
            "probation_months must be between 3 and 6 inclusive".into(),
        )));
    }

    let db = env
        .d1("DB")
        .map_err(|e| WorkerError::Internal(e.to_string()))?;

    // ── Load the application ─────────────────────────────────────────────────
    let application = db
        .prepare(
            "SELECT id, career_id, applicant_name, applicant_email, cover_letter, \
             status, applied_at, updated_at \
             FROM application WHERE id = ?1",
        )
        .bind(&[application_id.into()])
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?
        .first::<Application>(None)
        .await
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?
        .ok_or(WorkerError::NotFound)?;

    // Application must be in `Offered` status to be hired
    if application.status != ApplicationStatus::Offered {
        return error_to_response(WorkerError::Validation(ValidationError::InvalidTransition));
    }

    let applicant_email = application.applicant_email.clone();

    // Derive username from the email local-part (everything before @).
    // D1's DEFAULT generates the id; we provide the username here.
    let username = applicant_email
        .split('@')
        .next()
        .unwrap_or("staff")
        .to_lowercase();

    // ── Step 1: Update application status to 'Hired' ─────────────────────────
    db.prepare(
        "UPDATE application SET status = 'Hired', updated_at = unixepoch() WHERE id = ?1",
    )
    .bind(&[application_id.into()])
    .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?
    .run()
    .await
    .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?;

    // ── Step 2: Insert staff row ─────────────────────────────────────────────
    // id is generated by the D1 DEFAULT (lower(hex(randomblob(16)))).
    // We insert without an explicit id and then query back by email.
    let insert_staff_result = db
        .prepare(
            "INSERT INTO staff (email, username, role, onboarding_completed) \
             VALUES (?1, ?2, 'Staff', 0)",
        )
        .bind(&[applicant_email.as_str().into(), username.as_str().into()])
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?
        .run()
        .await;

    if let Err(e) = insert_staff_result {
        // Compensate: revert application status back to 'Offered'
        let _ = db
            .prepare(
                "UPDATE application SET status = 'Offered', updated_at = unixepoch() \
                 WHERE id = ?1",
            )
            .bind(&[application_id.into()])
            .map_err(|_| ())
            .and_then(|stmt| {
                // best-effort — ignore if this also fails
                drop(stmt);
                Ok(())
            });
        return error_to_response(WorkerError::Db(DbError::Query(e.to_string())));
    }

    // Retrieve the generated staff_id by looking up the email
    let staff_id_row = db
        .prepare("SELECT id FROM staff WHERE email = ?1")
        .bind(&[applicant_email.as_str().into()])
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?
        .first::<serde_json::Value>(None)
        .await
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?;

    let staff_id = match staff_id_row.and_then(|row| {
        row.get("id")
            .and_then(|v| v.as_str())
            .map(|s| s.to_string())
    }) {
        Some(id) => id,
        None => {
            // Compensate: revert application
            let _ = db
                .prepare(
                    "UPDATE application SET status = 'Offered', updated_at = unixepoch() \
                     WHERE id = ?1",
                )
                .bind(&[application_id.into()])
                .ok();
            return error_to_response(WorkerError::Internal(
                "Failed to retrieve generated staff_id after insert".into(),
            ));
        }
    };

    // ── Step 3: Insert staff_lifecycle row ───────────────────────────────────
    // probation_end = unixepoch() + probation_months * 30 * 86400
    let probation_seconds: i64 = probation_months as i64 * 30 * 86_400;

    let insert_lifecycle_result = db
        .prepare(
            "INSERT INTO staff_lifecycle (staff_id, status, probation_start, probation_end) \
             VALUES (?1, 'Probation', unixepoch(), unixepoch() + ?2)",
        )
        .bind(&[staff_id.as_str().into(), probation_seconds.into()])
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?
        .run()
        .await;

    if let Err(e) = insert_lifecycle_result {
        // Compensate: delete staff row and revert application
        let _ = db
            .prepare("DELETE FROM staff WHERE id = ?1")
            .bind(&[staff_id.as_str().into()])
            .ok();
        let _ = db
            .prepare(
                "UPDATE application SET status = 'Offered', updated_at = unixepoch() \
                 WHERE id = ?1",
            )
            .bind(&[application_id.into()])
            .ok();
        return error_to_response(WorkerError::Db(DbError::Query(e.to_string())));
    }

    // ── Step 4: Dispatch onboarding email ────────────────────────────────────
    // Email failure does not roll back the DB writes — the hire is complete;
    // the email can be retried by the admin if needed.
    if let Err(e) = send_onboarding_email(&applicant_email, &staff_id, env).await {
        // Log but do not surface to caller; hire transaction succeeded.
        console_warn!("hire_applicant: onboarding email failed for staff {}: {:?}", staff_id, e);
    }

    // ── Return HTTP 201 with staff_id ─────────────────────────────────────────
    Response::from_json(&serde_json::json!({ "staff_id": staff_id }))
        .map(|r| r.with_status(201))
        .map_err(|e| WorkerError::Internal(e.to_string()).into())
}

// ---------------------------------------------------------------------------
// POST /api/admin/staff/:id/confirm
// ---------------------------------------------------------------------------

/// Confirm a staff member, transitioning their lifecycle from Probation → Confirmed.
///
/// Returns HTTP 200 `{ "staff_id": "...", "status": "Confirmed" }`.
/// Returns HTTP 404 if no lifecycle record found.
/// Returns HTTP 400 if lifecycle status is not Probation.
///
/// Requires Admin role (enforced by router).
///
/// Requirements: 8.1, 8.2, 8.3, 8.4
pub async fn confirm_staff(
    _req: &Request,
    env: &Env,
    _ctx: SessionContext,
    staff_id: &str,
) -> Result<Response> {
    let db = env
        .d1("DB")
        .map_err(|e| WorkerError::Internal(e.to_string()))?;

    // ── Load current lifecycle status ────────────────────────────────────────
    let row = db
        .prepare(
            "SELECT id, staff_id, status, probation_start, probation_end, confirmed_at \
             FROM staff_lifecycle WHERE staff_id = ?1",
        )
        .bind(&[staff_id.into()])
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?
        .first::<serde_json::Value>(None)
        .await
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?;

    let lifecycle = match row {
        Some(v) => v,
        None => return error_to_response(WorkerError::NotFound),
    };

    // ── Validate: must be Probation (Req 8.2, 8.4) ──────────────────────────
    let current_status = lifecycle
        .get("status")
        .and_then(|v| v.as_str())
        .unwrap_or("");

    if current_status != "Probation" {
        return Response::from_json(&serde_json::json!({
            "error": "Invalid transition: lifecycle status must be Probation"
        }))
        .map(|r| r.with_status(400))
        .map_err(|e| e.into());
    }

    // ── Execute the Probation → Confirmed transition (Req 8.3) ───────────────
    db.prepare(
        "UPDATE staff_lifecycle SET status = 'Confirmed', confirmed_at = unixepoch() \
         WHERE staff_id = ?1",
    )
    .bind(&[staff_id.into()])
    .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?
    .run()
    .await
    .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?;

    Response::from_json(&serde_json::json!({
        "staff_id": staff_id,
        "status": "Confirmed"
    }))
    .map(|r| r.with_status(200))
    .map_err(|e| WorkerError::Internal(e.to_string()).into())
}

// ---------------------------------------------------------------------------
// PATCH /api/admin/staff/:id/role
// ---------------------------------------------------------------------------

/// Update the role of a staff member.
///
/// Request body: `{ "role": "Staff" | "Admin" | "SuperAdmin" }`.
/// Assigning `SuperAdmin` requires the caller to have `SuperAdmin` role (Req 8.7).
///
/// Returns HTTP 200 `{ "id": "...", "role": "..." }`.
/// Returns HTTP 400 for unknown role values.
/// Returns HTTP 403 if caller lacks SuperAdmin when assigning SuperAdmin.
/// Returns HTTP 404 if the staff member does not exist.
///
/// Requires Admin role (enforced by router); SuperAdmin check is done inline.
///
/// Requirements: 8.5, 8.6, 8.7
pub async fn patch_staff_role(
    mut req: Request,
    env: &Env,
    ctx: SessionContext,
    staff_id: &str,
) -> Result<Response> {
    use crate::models::staff::Role;

    // ── Parse body ───────────────────────────────────────────────────────────
    let body: serde_json::Value = req
        .json()
        .await
        .unwrap_or(serde_json::Value::Object(serde_json::Map::new()));

    let role_str = match body.get("role").and_then(|v| v.as_str()) {
        Some(s) => s.to_string(),
        None => {
            return error_to_response(WorkerError::Validation(ValidationError::InvalidInput(
                "role field is required".into(),
            )));
        }
    };

    // ── Validate role value (Req 8.5, 8.6) ──────────────────────────────────
    let role_int: i64 = match role_str.as_str() {
        "Staff" => 2,
        "Admin" => 3,
        "SuperAdmin" => 4,
        _ => {
            return error_to_response(WorkerError::Validation(ValidationError::InvalidInput(
                "role must be one of: Staff, Admin, SuperAdmin".into(),
            )));
        }
    };

    // ── SuperAdmin elevation check (Req 8.7) ─────────────────────────────────
    if role_str == "SuperAdmin" && ctx.role != Role::SuperAdmin {
        return error_to_response(WorkerError::Forbidden);
    }

    let db = env
        .d1("DB")
        .map_err(|e| WorkerError::Internal(e.to_string()))?;

    // ── Execute the role update ──────────────────────────────────────────────
    let result = db
        .prepare("UPDATE staff SET role = ?1, updated_at = unixepoch() WHERE id = ?2")
        .bind(&[role_int.into(), staff_id.into()])
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?
        .run()
        .await
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?;

    // ── 404 if no rows were affected ─────────────────────────────────────────
    let rows_written = result.meta().ok().flatten().and_then(|m| m.rows_written).unwrap_or(0);
    if rows_written == 0 {
        return error_to_response(WorkerError::NotFound);
    }

    Response::from_json(&serde_json::json!({
        "id": staff_id,
        "role": role_str
    }))
    .map(|r| r.with_status(200))
    .map_err(|e| WorkerError::Internal(e.to_string()).into())
}

// ---------------------------------------------------------------------------
// GET /api/admin/staff
// ---------------------------------------------------------------------------

/// Return all staff members ordered by `created_at ASC`.
///
/// Response is a JSON array of `StaffAdmin` objects (excludes `signing_public_key`).
///
/// Requires Admin role (enforced by router).
///
/// Requirements: 8.8 (list staff)
pub async fn list_staff(
    _req: &Request,
    env: &Env,
    _ctx: SessionContext,
) -> Result<Response> {
    use crate::models::staff::StaffAdmin;

    let db = env
        .d1("DB")
        .map_err(|e| WorkerError::Internal(e.to_string()))?;

    let results = db
        .prepare(
            "SELECT id, email, username, name, job_title, bio, avatar_url, \
             role, onboarding_completed, created_at, updated_at \
             FROM staff ORDER BY created_at ASC",
        )
        .all()
        .await
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?;

    let staff: Vec<StaffAdmin> = results
        .results::<StaffAdmin>()
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?;

    Response::from_json(&staff)
        .map(|r| r.with_status(200))
        .map_err(|e| WorkerError::Internal(e.to_string()).into())
}

// ---------------------------------------------------------------------------
// Content management helpers
// ---------------------------------------------------------------------------

// Bring std::result::Result into scope for functions returning two-type Results.
use std::result::Result as StdResult;

// ---------------------------------------------------------------------------
// POST /api/admin/content
// ---------------------------------------------------------------------------

/// Create a new content post (insight, work, or capability).
///
/// Request body: `{ type, title, summary?, body_md?, author_id? }`
///
/// - Validates `type ∈ {insight, work, capability}` → HTTP 400 on failure.
/// - Generates a URL-safe slug from `title`; appends `-2`, `-3`, … on collision.
/// - Inserts post row with `published = 0`.
/// - Returns HTTP 201 with the created post JSON.
///
/// Requires Admin role (enforced by router).
///
/// Requirements: 10.5, 10.8
pub async fn create_content(mut req: Request, env: &Env, _ctx: SessionContext) -> Result<Response> {
    let body: serde_json::Value = req
        .json()
        .await
        .unwrap_or(serde_json::Value::Object(serde_json::Map::new()));

    // ── Parse and validate fields ────────────────────────────────────────────
    let post_type = body
        .get("type")
        .and_then(|v| v.as_str())
        .unwrap_or("")
        .trim()
        .to_string();

    if !["insight", "work", "capability"].contains(&post_type.as_str()) {
        return error_to_response(WorkerError::Validation(ValidationError::InvalidInput(
            "type must be one of: insight, work, capability".into(),
        )));
    }

    let title = body
        .get("title")
        .and_then(|v| v.as_str())
        .unwrap_or("")
        .trim()
        .to_string();

    if title.is_empty() {
        return error_to_response(WorkerError::Validation(ValidationError::InvalidInput(
            "title is required".into(),
        )));
    }

    let summary = body
        .get("summary")
        .and_then(|v| v.as_str())
        .unwrap_or("")
        .to_string();

    let body_md = body
        .get("body_md")
        .and_then(|v| v.as_str())
        .unwrap_or("")
        .to_string();

    let author_id: Option<String> = body
        .get("author_id")
        .and_then(|v| v.as_str())
        .map(|s| s.to_string());

    let db = env
        .d1("DB")
        .map_err(|e| WorkerError::Internal(e.to_string()))?;

    // ── Generate unique slug ─────────────────────────────────────────────────
    // Base slug: lowercase, spaces → '-', strip non-alphanumeric except '-'.
    let base_slug = generate_slug(&title);

    // Ensure uniqueness per type; append -2, -3, … on collision.
    let slug = find_unique_slug(&db, &base_slug, &post_type, None).await?;

    // ── Insert post row (published = 0) ──────────────────────────────────────
    let author_id_value: wasm_bindgen::JsValue = match &author_id {
        Some(id) => id.as_str().into(),
        None => wasm_bindgen::JsValue::NULL,
    };

    db.prepare(
        "INSERT INTO post (type, slug, title, summary, body_md, author_id, published, \
         featured_image_url, category, tags, project_type, technologies, material_icon) \
         VALUES (?1, ?2, ?3, ?4, ?5, ?6, 0, ?7, ?8, ?9, ?10, ?11, ?12)",
    )
    .bind(&[
        post_type.as_str().into(),
        slug.as_str().into(),
        title.as_str().into(),
        summary.as_str().into(),
        body_md.as_str().into(),
        author_id_value,
        body.get("featured_image_url").and_then(|v| v.as_str()).unwrap_or("").to_string().into(),
        body.get("category").and_then(|v| v.as_str()).unwrap_or("").to_string().into(),
        body.get("tags").and_then(|v| v.as_str()).unwrap_or("").to_string().into(),
        body.get("project_type").and_then(|v| v.as_str()).unwrap_or("").to_string().into(),
        body.get("technologies").and_then(|v| v.as_str()).unwrap_or("").to_string().into(),
        body.get("material_icon").and_then(|v| v.as_str()).unwrap_or("").to_string().into(),
    ])
    .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?
    .run()
    .await
    .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?;

    // ── Re-query the inserted row ────────────────────────────────────────────
    let post = db
        .prepare(
            "SELECT id, type, slug, title, summary, body_md, author_id, \
             published_at, updated_at, published, \
             featured_image_url, category, tags, project_type, technologies, material_icon \
             FROM post WHERE slug = ?1 AND type = ?2",
        )
        .bind(&[slug.as_str().into(), post_type.as_str().into()])
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?
        .first::<serde_json::Value>(None)
        .await
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?
        .ok_or_else(|| WorkerError::Internal("Post row missing after insert".into()))?;

    Response::from_json(&post)
        .map(|r| r.with_status(201))
        .map_err(|e| WorkerError::Internal(e.to_string()).into())
}

// ---------------------------------------------------------------------------
// PATCH /api/admin/content/:id
// ---------------------------------------------------------------------------

/// Update an existing content post.
///
/// Accepts any subset of `{ title, summary, body_md, published, published_at, slug }`.
/// If `slug` is updated, checks uniqueness within the same `type`
/// (excluding the current post id); returns HTTP 409 on conflict.
/// Always refreshes `updated_at = unixepoch()`.
/// Returns HTTP 200 with the updated post JSON.
///
/// Requires Admin role (enforced by router).
///
/// Requirements: 10.6, 10.8
pub async fn patch_content(mut req: Request, env: &Env, _ctx: SessionContext, id: &str) -> Result<Response> {
    let body: serde_json::Value = req
        .json()
        .await
        .unwrap_or(serde_json::Value::Object(serde_json::Map::new()));

    let db = env
        .d1("DB")
        .map_err(|e| WorkerError::Internal(e.to_string()))?;

    // ── Load current post (need type for slug uniqueness check) ──────────────
    let current = db
        .prepare(
            "SELECT id, type, slug, title, summary, body_md, author_id, \
             published_at, updated_at, published, \
             featured_image_url, category, tags, project_type, technologies, material_icon \
             FROM post WHERE id = ?1",
        )
        .bind(&[id.into()])
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?
        .first::<serde_json::Value>(None)
        .await
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?
        .ok_or(WorkerError::NotFound)?;

    let post_type = current
        .get("type")
        .and_then(|v| v.as_str())
        .unwrap_or("")
        .to_string();

    // ── Validate slug uniqueness if slug is being updated (Req 10.8) ─────────
    if let Some(new_slug) = body.get("slug").and_then(|v| v.as_str()) {
        let conflict = db
            .prepare(
                "SELECT id FROM post WHERE slug = ?1 AND type = ?2 AND id != ?3 LIMIT 1",
            )
            .bind(&[new_slug.into(), post_type.as_str().into(), id.into()])
            .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?
            .first::<serde_json::Value>(None)
            .await
            .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?;

        if conflict.is_some() {
            return Response::from_json(&serde_json::json!({ "error": "Slug already in use for this post type" }))
                .map(|r| r.with_status(409))
                .map_err(|e| e.into());
        }
    }

    // ── Build dynamic SET clause ─────────────────────────────────────────────
    let mut set_clauses: Vec<String> = Vec::new();
    let mut bindings: Vec<wasm_bindgen::JsValue> = Vec::new();
    let mut param_idx: u32 = 1;

    macro_rules! push_str_field {
        ($json_key:expr, $col:expr) => {
            if let Some(val) = body.get($json_key).and_then(|v| v.as_str()) {
                set_clauses.push(format!("{} = ?{}", $col, param_idx));
                bindings.push(val.to_string().into());
                param_idx += 1;
            }
        };
    }

    push_str_field!("title",    "title");
    push_str_field!("summary",  "summary");
    push_str_field!("body_md",  "body_md");
    push_str_field!("slug",     "slug");
    push_str_field!("featured_image_url", "featured_image_url");
    push_str_field!("category",           "category");
    push_str_field!("tags",               "tags");
    push_str_field!("project_type",       "project_type");
    push_str_field!("technologies",       "technologies");
    push_str_field!("material_icon",      "material_icon");

    // published is bool → stored as integer
    if let Some(published) = body.get("published").and_then(|v| v.as_bool()) {
        let val: i64 = if published { 1 } else { 0 };
        set_clauses.push(format!("published = ?{}", param_idx));
        bindings.push(val.into());
        param_idx += 1;
    }

    // published_at is an optional integer
    if let Some(published_at) = body.get("published_at").and_then(|v| v.as_i64()) {
        set_clauses.push(format!("published_at = ?{}", param_idx));
        bindings.push(published_at.into());
        param_idx += 1;
    }

    if set_clauses.is_empty() {
        return error_to_response(WorkerError::Validation(ValidationError::InvalidInput(
            "No updatable fields provided".into(),
        )));
    }

    // Always refresh updated_at (Req 10.6)
    set_clauses.push("updated_at = unixepoch()".to_string());

    let sql = format!(
        "UPDATE post SET {} WHERE id = ?{}",
        set_clauses.join(", "),
        param_idx
    );
    bindings.push(id.to_string().into());

    db.prepare(&sql)
        .bind(&bindings)
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?
        .run()
        .await
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?;

    // ── Re-query and return updated row ──────────────────────────────────────
    let post = db
        .prepare(
            "SELECT id, type, slug, title, summary, body_md, author_id, \
             published_at, updated_at, published, \
             featured_image_url, category, tags, project_type, technologies, material_icon \
             FROM post WHERE id = ?1",
        )
        .bind(&[id.into()])
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?
        .first::<serde_json::Value>(None)
        .await
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?
        .ok_or(WorkerError::NotFound)?;

    Response::from_json(&post)
        .map(|r| r.with_status(200))
        .map_err(|e| WorkerError::Internal(e.to_string()).into())
}

// ---------------------------------------------------------------------------
// DELETE /api/admin/content/:id
// ---------------------------------------------------------------------------

/// Delete a content post by id.
///
/// Returns HTTP 204 with no body.
///
/// Requires SuperAdmin role (enforced by router).
///
/// Requirements: 10.7
pub async fn delete_content(_req: &Request, env: &Env, _ctx: SessionContext, id: &str) -> Result<Response> {
    let db = env
        .d1("DB")
        .map_err(|e| WorkerError::Internal(e.to_string()))?;

    db.prepare("DELETE FROM post WHERE id = ?1")
        .bind(&[id.into()])
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?
        .run()
        .await
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?;

    // HTTP 204 — no body
    Response::empty()
        .map(|r| r.with_status(204))
        .map_err(|e| WorkerError::Internal(e.to_string()).into())
}

// ---------------------------------------------------------------------------
// Slug generation helpers
// ---------------------------------------------------------------------------

/// Generate a URL-safe slug from a title string.
///
/// Transformation: lowercase, spaces → `-`, strip non-alphanumeric except `-`.
fn generate_slug(title: &str) -> String {
    title
        .to_lowercase()
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() || c == '-' { c } else if c == ' ' { '-' } else { '\0' })
        .filter(|&c| c != '\0')
        .collect::<String>()
        // Collapse consecutive hyphens
        .split('-')
        .filter(|s| !s.is_empty())
        .collect::<Vec<&str>>()
        .join("-")
}

/// Find the first available slug for a given `post_type`, starting from
/// `base_slug` and appending `-2`, `-3`, … until no collision is found.
///
/// If `exclude_id` is provided the slug check ignores that post row (used
/// during PATCH to allow keeping the same slug).
///
/// Requirements: 10.5, 10.8
async fn find_unique_slug(
    db: &D1Database,
    base_slug: &str,
    post_type: &str,
    exclude_id: Option<&str>,
) -> StdResult<String, WorkerError> {
    let mut candidate = base_slug.to_string();
    let mut counter: u32 = 1;

    loop {
        let conflict = match exclude_id {
            Some(eid) => {
                db.prepare(
                    "SELECT id FROM post WHERE slug = ?1 AND type = ?2 AND id != ?3 LIMIT 1",
                )
                .bind(&[candidate.as_str().into(), post_type.into(), eid.into()])
                .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?
                .first::<serde_json::Value>(None)
                .await
                .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?
            }
            None => {
                db.prepare(
                    "SELECT id FROM post WHERE slug = ?1 AND type = ?2 LIMIT 1",
                )
                .bind(&[candidate.as_str().into(), post_type.into()])
                .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?
                .first::<serde_json::Value>(None)
                .await
                .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?
            }
        };

        if conflict.is_none() {
            return Ok(candidate);
        }

        counter += 1;
        candidate = format!("{}-{}", base_slug, counter);

        // Safety guard: prevent infinite loops if something goes very wrong.
        if counter > 1000 {
            return Err(WorkerError::Internal(
                "Could not find unique slug after 1000 attempts".into(),
            ));
        }    }
}

// ---------------------------------------------------------------------------
// Shared multipart upload helper
// ---------------------------------------------------------------------------

/// Parse a multipart form, read the `file` field, detect MIME from magic bytes,
/// validate MIME is in `allowed_mimes`, and validate `size <= max_size`.
///
/// Returns `(bytes, original_filename, detected_mime)` on success, or an
/// HTTP 400 `Result<Response>` on failure.
async fn parse_and_validate_image_upload(
    req: &mut Request,
    allowed_mimes: &[&str],
    max_size: usize,
) -> std::result::Result<(Vec<u8>, String, &'static str), Result<Response>> {
    // Parse multipart form
    let form = req
        .form_data()
        .await
        .map_err(|e| {
            Response::from_json(&serde_json::json!({ "error": format!("Failed to parse form data: {}", e) }))
                .map(|r| r.with_status(400))
                .map_err(|e2| WorkerError::Internal(e2.to_string()).into())
        })?;

    // Extract `file` field
    let (file_bytes, original_filename) = match form.get("file") {
        Some(FormEntry::File(file)) => {
            let name = file.name();
            let bytes = file.bytes().await.map_err(|e| {
                Response::from_json(&serde_json::json!({ "error": format!("Failed to read file: {}", e) }))
                    .map(|r| r.with_status(400))
                    .map_err(|e2| WorkerError::Internal(e2.to_string()).into())
            })?;
            (bytes, name)
        }
        _ => {
            return Err(
                Response::from_json(&serde_json::json!({ "error": "file field is required" }))
                    .map(|r| r.with_status(400))
                    .map_err(|e| WorkerError::Internal(e.to_string()).into()),
            );
        }
    };

    // Detect MIME from magic bytes (Req 12.2)
    let mime = match detect_mime_from_magic_bytes(&file_bytes) {
        Some(m) if allowed_mimes.contains(&m) => m,
        _ => {
            return Err(
                Response::from_json(&serde_json::json!({ "error": "Invalid image type" }))
                    .map(|r| r.with_status(400))
                    .map_err(|e| WorkerError::Internal(e.to_string()).into()),
            );
        }
    };

    // Validate file size (Req 12.4, 12.5)
    if file_bytes.len() > max_size {
        return Err(
            Response::from_json(&serde_json::json!({ "error": "File too large" }))
                .map(|r| r.with_status(400))
                .map_err(|e| WorkerError::Internal(e.to_string()).into()),
        );
    }

    Ok((file_bytes, original_filename, mime))
}

// ---------------------------------------------------------------------------
// POST /api/upload/avatar
// ---------------------------------------------------------------------------

/// Upload a staff avatar image.
///
/// Accepts `multipart/form-data` with a `file` field.
/// Validates MIME type via magic bytes (must be image/jpeg, image/png, image/webp, image/avif).
/// Validates file size ≤ 4 MB.
/// Stores at `avatars/{staff_id}.{ext}`.
/// Returns HTTP 200 `{ "url": "<cdn-url>" }`.
///
/// Requires Staff role (enforced by router).
///
/// Requirements: 12.1, 12.2, 12.3, 12.4, 12.5, 12.6, 12.7, 12.8
pub async fn handle_upload_avatar(
    mut req: Request,
    ctx: SessionContext,
    env: &Env,
) -> Result<Response> {
    let bucket = env
        .bucket("EZO_MEDIA")
        .map_err(|e| WorkerError::Internal(format!("Failed to get R2 bucket: {}", e)))?;

    let (bytes, _filename, mime) =
        match parse_and_validate_image_upload(&mut req, ALLOWED_IMAGE_MIMES, MAX_IMAGE_SIZE).await {
            Ok(v) => v,
            Err(resp) => return resp,
        };

    let ext = extension_from_mime(mime);
    let key = format!("avatars/{}.{}", ctx.staff_id, ext);

    let url = r2_put_public(
        &bucket,
        &key,
        bytes,
        mime,
        "public, max-age=31536000, immutable",
    )
    .await
    .map_err(|e| WorkerError::Internal(format!("R2 upload failed: {:?}", e)))?;

    Response::from_json(&serde_json::json!({ "url": url }))
        .map(|r| r.with_status(200))
        .map_err(|e| WorkerError::Internal(e.to_string()).into())
}

// ---------------------------------------------------------------------------
// POST /api/upload/post/:id/cover
// ---------------------------------------------------------------------------

/// Upload a post cover image.
///
/// Accepts `multipart/form-data` with a `file` field.
/// Validates MIME and size (≤ 4 MB).
/// Stores at `posts/{post_id}/cover.{ext}`.
/// Returns HTTP 200 `{ "url": "<cdn-url>" }`.
///
/// Requires Admin role (enforced by router).
///
/// Requirements: 12.1, 12.2, 12.3, 12.4, 12.5, 12.6, 12.7, 12.8
pub async fn handle_upload_post_cover(
    post_id: &str,
    mut req: Request,
    _ctx: SessionContext,
    env: &Env,
) -> Result<Response> {
    let bucket = env
        .bucket("EZO_MEDIA")
        .map_err(|e| WorkerError::Internal(format!("Failed to get R2 bucket: {}", e)))?;

    let (bytes, _filename, mime) =
        match parse_and_validate_image_upload(&mut req, ALLOWED_IMAGE_MIMES, MAX_IMAGE_SIZE).await {
            Ok(v) => v,
            Err(resp) => return resp,
        };

    let ext = extension_from_mime(mime);
    let key = format!("posts/{}/cover.{}", post_id, ext);

    let url = r2_put_public(
        &bucket,
        &key,
        bytes,
        mime,
        "public, max-age=31536000, immutable",
    )
    .await
    .map_err(|e| WorkerError::Internal(format!("R2 upload failed: {:?}", e)))?;

    Response::from_json(&serde_json::json!({ "url": url }))
        .map(|r| r.with_status(200))
        .map_err(|e| WorkerError::Internal(e.to_string()).into())
}

// ---------------------------------------------------------------------------
// POST /api/upload/post/:id/media
// ---------------------------------------------------------------------------

/// Upload inline post media.
///
/// Accepts `multipart/form-data` with a `file` field.
/// Validates MIME and size (≤ 4 MB).
/// Sanitises the original filename.
/// Stores at `posts/{post_id}/media/{sanitised_filename}`.
/// Returns HTTP 200 `{ "url": "<cdn-url>" }`.
///
/// Requires Admin role (enforced by router).
///
/// Requirements: 12.1, 12.2, 12.3, 12.4, 12.5, 12.6, 12.7, 12.8
pub async fn handle_upload_post_media(
    post_id: &str,
    mut req: Request,
    _ctx: SessionContext,
    env: &Env,
) -> Result<Response> {
    let bucket = env
        .bucket("EZO_MEDIA")
        .map_err(|e| WorkerError::Internal(format!("Failed to get R2 bucket: {}", e)))?;

    let (bytes, original_filename, mime) =
        match parse_and_validate_image_upload(&mut req, ALLOWED_IMAGE_MIMES, MAX_IMAGE_SIZE).await {
            Ok(v) => v,
            Err(resp) => return resp,
        };

    let sanitised = sanitise_filename(&original_filename);
    let key = format!("posts/{}/media/{}", post_id, sanitised);

    let url = r2_put_public(
        &bucket,
        &key,
        bytes,
        mime,
        "public, max-age=31536000, immutable",
    )
    .await
    .map_err(|e| WorkerError::Internal(format!("R2 upload failed: {:?}", e)))?;

    Response::from_json(&serde_json::json!({ "url": url }))
        .map(|r| r.with_status(200))
        .map_err(|e| WorkerError::Internal(e.to_string()).into())
}

// ---------------------------------------------------------------------------
// POST /api/upload/career/:id/hero
// ---------------------------------------------------------------------------

/// Upload a career listing hero image.
///
/// Accepts `multipart/form-data` with a `file` field.
/// Validates MIME and size (≤ 4 MB).
/// Stores at `careers/{career_id}/hero.{ext}`.
/// Returns HTTP 200 `{ "url": "<cdn-url>" }`.
///
/// Requires Admin role (enforced by router).
///
/// Requirements: 12.1, 12.2, 12.3, 12.4, 12.5, 12.6, 12.7, 12.8
pub async fn handle_upload_career_hero(
    career_id: &str,
    mut req: Request,
    _ctx: SessionContext,
    env: &Env,
) -> Result<Response> {
    let bucket = env
        .bucket("EZO_MEDIA")
        .map_err(|e| WorkerError::Internal(format!("Failed to get R2 bucket: {}", e)))?;

    let (bytes, _filename, mime) =
        match parse_and_validate_image_upload(&mut req, ALLOWED_IMAGE_MIMES, MAX_IMAGE_SIZE).await {
            Ok(v) => v,
            Err(resp) => return resp,
        };

    let ext = extension_from_mime(mime);
    let key = format!("careers/{}/hero.{}", career_id, ext);

    let url = r2_put_public(
        &bucket,
        &key,
        bytes,
        mime,
        "public, max-age=31536000, immutable",
    )
    .await
    .map_err(|e| WorkerError::Internal(format!("R2 upload failed: {:?}", e)))?;

    Response::from_json(&serde_json::json!({ "url": url }))
        .map(|r| r.with_status(200))
        .map_err(|e| WorkerError::Internal(e.to_string()).into())
}

// ---------------------------------------------------------------------------
// GET /api/admin/applications/:id/documents
// ---------------------------------------------------------------------------

/// Return metadata for all documents attached to an application.
///
/// Queries `application_document` for rows matching `application_id`,
/// and returns a `DocumentMeta[]` JSON array.
///
/// Requires Admin role (enforced by router).
///
/// Requirements: 12.12
pub async fn handle_get_application_documents(
    application_id: &str,
    _ctx: SessionContext,
    env: &Env,
) -> Result<Response> {
    let db = env
        .d1("DB")
        .map_err(|e| WorkerError::Internal(e.to_string()))?;

    let results = db
        .prepare(
            "SELECT id, application_id, original_filename, mime_type, uploaded_at \
             FROM application_document WHERE application_id = ?1 ORDER BY uploaded_at ASC",
        )
        .bind(&[application_id.into()])
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?
        .all()
        .await
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?;

    let docs: Vec<DocumentMeta> = results
        .results::<DocumentMeta>()
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?;

    Response::from_json(&docs)
        .map(|r| r.with_status(200))
        .map_err(|e| WorkerError::Internal(e.to_string()).into())
}

// ---------------------------------------------------------------------------
// GET /api/admin/applications/:id/documents/:doc_id/url
// ---------------------------------------------------------------------------

/// Generate a time-limited presigned URL for a specific application document.
///
/// 1. Queries D1 to fetch `r2_key` for the given `doc_id` + `application_id`.
/// 2. Returns HTTP 404 if not found.
/// 3. Validates `r2_key.starts_with("applications/")` → HTTP 403 if not.
/// 4. Calls `generate_presigned_url` with TTL 300 seconds.
/// 5. Returns `{ "url": "<presigned>", "expires_at": <unix_timestamp> }`.
///
/// Requires Admin role (enforced by router).
///
/// Requirements: 12.9, 12.10, 12.11
pub async fn handle_get_document_presigned_url(
    application_id: &str,
    doc_id: &str,
    _ctx: SessionContext,
    env: &Env,
) -> Result<Response> {
    let db = env
        .d1("DB")
        .map_err(|e| WorkerError::Internal(e.to_string()))?;

    // Query the r2_key for this specific document belonging to this application
    let row = db
        .prepare(
            "SELECT r2_key FROM application_document \
             WHERE id = ?1 AND application_id = ?2",
        )
        .bind(&[doc_id.into(), application_id.into()])
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?
        .first::<serde_json::Value>(None)
        .await
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?;

    let r2_key = match row.and_then(|v| {
        v.get("r2_key")
            .and_then(|k| k.as_str())
            .map(|s| s.to_string())
    }) {
        Some(k) => k,
        None => return error_to_response(WorkerError::NotFound),
    };

    // Security: only allow keys under applications/ (Req 12.11)
    if !r2_key.starts_with("applications/") {
        return error_to_response(WorkerError::Forbidden);
    }

    let bucket = env
        .bucket("EZO_MEDIA")
        .map_err(|e| WorkerError::Internal(format!("Failed to get R2 bucket: {}", e)))?;

    // Generate presigned URL with 300-second TTL
    let presigned_url = generate_presigned_url(&bucket, &r2_key, 300)
        .await
        .map_err(|e| WorkerError::Internal(format!("Presigned URL generation failed: {:?}", e)))?;

    // Compute expiry: current unix time + 300 seconds
    let expires_at = now_unix() + 300;

    Response::from_json(&serde_json::json!({
        "url": presigned_url,
        "expires_at": expires_at,
    }))
    .map(|r| r.with_status(200))
    .map_err(|e| WorkerError::Internal(e.to_string()).into())
}

// ---------------------------------------------------------------------------
// now_unix helper
// ---------------------------------------------------------------------------

/// Return the current Unix timestamp in seconds.
///
/// Uses the Workers `Date` API available from `worker::Date`.
fn now_unix() -> i64 {
    // Date::now().as_millis() returns u64 milliseconds since epoch
    (Date::now().as_millis() / 1000) as i64
}

// ---------------------------------------------------------------------------
// Client logo handlers
// ---------------------------------------------------------------------------

/// GET /api/clients  — public list of active client logos.
pub async fn list_clients_public(_req: &Request, env: &Env) -> Result<Response> {
    let db = env.d1("DB").map_err(|e| WorkerError::Internal(e.to_string()))?;
    let results = db
        .prepare(
            "SELECT id, name, logo_url, website_url, sort_order, active, created_at \
             FROM client_logo WHERE active = 1 ORDER BY sort_order ASC, created_at ASC",
        )
        .all()
        .await
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?;
    let rows: Vec<serde_json::Value> = results
        .results::<serde_json::Value>()
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?;
    Response::from_json(&rows)
        .map(|r| r.with_status(200))
        .map_err(|e| WorkerError::Internal(e.to_string()).into())
}

/// GET /api/admin/clients  — all client logos (admin).
pub async fn list_clients(_req: &Request, env: &Env, _ctx: SessionContext) -> Result<Response> {
    let db = env.d1("DB").map_err(|e| WorkerError::Internal(e.to_string()))?;
    let results = db
        .prepare(
            "SELECT id, name, logo_url, website_url, sort_order, active, created_at \
             FROM client_logo ORDER BY sort_order ASC, created_at ASC",
        )
        .all()
        .await
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?;
    let rows: Vec<serde_json::Value> = results
        .results::<serde_json::Value>()
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?;
    Response::from_json(&rows)
        .map(|r| r.with_status(200))
        .map_err(|e| WorkerError::Internal(e.to_string()).into())
}

/// POST /api/admin/clients
pub async fn create_client(mut req: Request, env: &Env, _ctx: SessionContext) -> Result<Response> {
    let body: serde_json::Value = req
        .json().await
        .unwrap_or(serde_json::Value::Object(serde_json::Map::new()));
    let name = body.get("name").and_then(|v| v.as_str()).unwrap_or("").trim().to_string();
    let logo_url = body.get("logo_url").and_then(|v| v.as_str()).unwrap_or("").trim().to_string();
    if name.is_empty() || logo_url.is_empty() {
        return error_to_response(WorkerError::Validation(
            ValidationError::InvalidInput("name and logo_url are required".into()),
        ));
    }
    let website_url = body.get("website_url").and_then(|v| v.as_str()).unwrap_or("").to_string();
    let sort_order = body.get("sort_order").and_then(|v| v.as_i64()).unwrap_or(0);
    let active: i64 = if body.get("active").and_then(|v| v.as_bool()).unwrap_or(true) { 1 } else { 0 };
    let db = env.d1("DB").map_err(|e| WorkerError::Internal(e.to_string()))?;
    db.prepare(
        "INSERT INTO client_logo (name, logo_url, website_url, sort_order, active) \
         VALUES (?1, ?2, ?3, ?4, ?5)",
    )
    .bind(&[name.as_str().into(), logo_url.as_str().into(),
             website_url.as_str().into(), sort_order.into(), active.into()])
    .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?
    .run().await
    .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?;
    let row = db
        .prepare("SELECT id, name, logo_url, website_url, sort_order, active, created_at \
                  FROM client_logo WHERE name = ?1 ORDER BY created_at DESC LIMIT 1")
        .bind(&[name.as_str().into()])
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?
        .first::<serde_json::Value>(None).await
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?
        .ok_or_else(|| WorkerError::Internal("Row missing after insert".into()))?;
    Response::from_json(&row)
        .map(|r| r.with_status(201))
        .map_err(|e| WorkerError::Internal(e.to_string()).into())
}

/// PATCH /api/admin/clients/:id
pub async fn patch_client(mut req: Request, env: &Env, _ctx: SessionContext, id: &str) -> Result<Response> {
    let body: serde_json::Value = req
        .json().await
        .unwrap_or(serde_json::Value::Object(serde_json::Map::new()));
    let db = env.d1("DB").map_err(|e| WorkerError::Internal(e.to_string()))?;
    let mut set_clauses: Vec<String> = Vec::new();
    let mut bindings: Vec<wasm_bindgen::JsValue> = Vec::new();
    let mut idx: u32 = 1;
    macro_rules! push_str {
        ($key:expr, $col:expr) => {
            if let Some(v) = body.get($key).and_then(|v| v.as_str()) {
                set_clauses.push(format!("{} = ?{}", $col, idx));
                bindings.push(v.to_string().into()); idx += 1;
            }
        };
    }
    push_str!("name",        "name");
    push_str!("logo_url",    "logo_url");
    push_str!("website_url", "website_url");
    if let Some(n) = body.get("sort_order").and_then(|v| v.as_i64()) {
        set_clauses.push(format!("sort_order = ?{}", idx)); bindings.push(n.into()); idx += 1;
    }
    if let Some(b) = body.get("active").and_then(|v| v.as_bool()) {
        let v: i64 = if b { 1 } else { 0 };
        set_clauses.push(format!("active = ?{}", idx)); bindings.push(v.into()); idx += 1;
    }
    if set_clauses.is_empty() {
        return error_to_response(WorkerError::Validation(ValidationError::InvalidInput("No fields provided".into())));
    }
    let sql = format!("UPDATE client_logo SET {} WHERE id = ?{}", set_clauses.join(", "), idx);
    bindings.push(id.to_string().into());
    db.prepare(&sql).bind(&bindings)
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?
        .run().await
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?;
    let row = db
        .prepare("SELECT id, name, logo_url, website_url, sort_order, active, created_at \
                  FROM client_logo WHERE id = ?1")
        .bind(&[id.into()])
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?
        .first::<serde_json::Value>(None).await
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?
        .ok_or(WorkerError::NotFound)?;
    Response::from_json(&row)
        .map(|r| r.with_status(200))
        .map_err(|e| WorkerError::Internal(e.to_string()).into())
}

/// DELETE /api/admin/clients/:id
pub async fn delete_client(_req: &Request, env: &Env, _ctx: SessionContext, id: &str) -> Result<Response> {
    let db = env.d1("DB").map_err(|e| WorkerError::Internal(e.to_string()))?;
    db.prepare("DELETE FROM client_logo WHERE id = ?1")
        .bind(&[id.into()])
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?
        .run().await
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?;
    Response::empty().map(|r| r.with_status(204))
        .map_err(|e| WorkerError::Internal(e.to_string()).into())
}

/// POST /api/upload/client/:id/logo
pub async fn handle_upload_client_logo(
    client_id: &str,
    mut req: Request,
    _ctx: SessionContext,
    env: &Env,
) -> Result<Response> {
    let bucket = env.bucket("EZO_MEDIA")
        .map_err(|e| WorkerError::Internal(format!("R2 bucket error: {}", e)))?;
    let (bytes, _filename, mime) =
        match parse_and_validate_image_upload(&mut req, ALLOWED_IMAGE_MIMES, MAX_IMAGE_SIZE).await {
            Ok(v) => v,
            Err(resp) => return resp,
        };
    let ext = extension_from_mime(mime);
    let key = format!("clients/{}/logo.{}", client_id, ext);
    let url = r2_put_public(&bucket, &key, bytes, mime, "public, max-age=31536000, immutable")
        .await
        .map_err(|e| WorkerError::Internal(format!("R2 upload failed: {:?}", e)))?;
    Response::from_json(&serde_json::json!({ "url": url }))
        .map(|r| r.with_status(200))
        .map_err(|e| WorkerError::Internal(e.to_string()).into())
}

// ---------------------------------------------------------------------------
// Post team member handlers
// ---------------------------------------------------------------------------

/// GET /api/admin/content/:post_id/team
pub async fn list_post_team(_req: &Request, env: &Env, _ctx: SessionContext, post_id: &str) -> Result<Response> {
    let db = env.d1("DB").map_err(|e| WorkerError::Internal(e.to_string()))?;
    let results = db
        .prepare(
            "SELECT ptm.id, ptm.post_id, ptm.staff_id, \
                    s.name AS staff_name, s.username AS staff_username, s.avatar_url AS staff_avatar_url, \
                    ptm.ext_name, ptm.ext_role, ptm.ext_url, ptm.sort_order \
             FROM post_team_member ptm \
             LEFT JOIN staff s ON ptm.staff_id = s.id \
             WHERE ptm.post_id = ?1 \
             ORDER BY ptm.sort_order ASC",
        )
        .bind(&[post_id.into()])
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?
        .all().await
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?;
    let rows: Vec<serde_json::Value> = results
        .results::<serde_json::Value>()
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?;
    Response::from_json(&rows)
        .map(|r| r.with_status(200))
        .map_err(|e| WorkerError::Internal(e.to_string()).into())
}

/// POST /api/admin/content/:post_id/team
pub async fn add_post_team_member(mut req: Request, env: &Env, _ctx: SessionContext, post_id: &str) -> Result<Response> {
    let body: serde_json::Value = req
        .json().await
        .unwrap_or(serde_json::Value::Object(serde_json::Map::new()));
    let staff_id: Option<String> = body.get("staff_id").and_then(|v| v.as_str()).map(|s| s.to_string());
    let ext_name = body.get("ext_name").and_then(|v| v.as_str()).unwrap_or("").to_string();
    let ext_role = body.get("ext_role").and_then(|v| v.as_str()).unwrap_or("").to_string();
    let ext_url  = body.get("ext_url").and_then(|v| v.as_str()).unwrap_or("").to_string();
    let sort_order = body.get("sort_order").and_then(|v| v.as_i64()).unwrap_or(0);
    if staff_id.is_none() && ext_name.is_empty() {
        return error_to_response(WorkerError::Validation(
            ValidationError::InvalidInput("Either staff_id or ext_name is required".into()),
        ));
    }
    let db = env.d1("DB").map_err(|e| WorkerError::Internal(e.to_string()))?;
    let staff_id_val: wasm_bindgen::JsValue = match &staff_id {
        Some(id) => id.as_str().into(),
        None => wasm_bindgen::JsValue::NULL,
    };
    db.prepare(
        "INSERT INTO post_team_member (post_id, staff_id, ext_name, ext_role, ext_url, sort_order) \
         VALUES (?1, ?2, ?3, ?4, ?5, ?6)",
    )
    .bind(&[post_id.into(), staff_id_val,
             ext_name.as_str().into(), ext_role.as_str().into(),
             ext_url.as_str().into(), sort_order.into()])
    .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?
    .run().await
    .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?;
    Response::from_json(&serde_json::json!({ "ok": true }))
        .map(|r| r.with_status(201))
        .map_err(|e| WorkerError::Internal(e.to_string()).into())
}

/// DELETE /api/admin/content/:post_id/team/:member_id
pub async fn remove_post_team_member(_req: &Request, env: &Env, _ctx: SessionContext, post_id: &str, member_id: &str) -> Result<Response> {
    let db = env.d1("DB").map_err(|e| WorkerError::Internal(e.to_string()))?;
    db.prepare("DELETE FROM post_team_member WHERE id = ?1 AND post_id = ?2")
        .bind(&[member_id.into(), post_id.into()])
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?
        .run().await
        .map_err(|e| WorkerError::Db(DbError::Query(e.to_string())))?;
    Response::empty().map(|r| r.with_status(204))
        .map_err(|e| WorkerError::Internal(e.to_string()).into())
}
